name = "log-app"
main = "src/index.ts"
compatibility_date = "2023-08-19"
account_id = "f1d77fc5d4e2a77d0937f1445d34585a"

compatibility_flags = [ "nodejs_compat" ]

[vars]
SUPABASE_URL = "qzfjblxdroqrmlheoajw.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6ZmpibHhkcm9xcm1saGVvYWp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODA4NTMwMzMsImV4cCI6MTk5NjQyOTAzM30.BM_qkpX-egNdiMc0PDO_34bIaXHB7ewnr2k4U2hGFMM"